<?php

// Admin Links
$locale['200'] = $settings['sitename']." Adminbereich";
$locale['ac00'] = "Administrations &Uuml;bersicht";
$locale['ac01'] = "Content Admin";
$locale['ac02'] = "User Admin";
$locale['ac03'] = "System Admin";
$locale['ac04'] = "Einstellungen";
$locale['ac05'] = "Infusions";
$locale['201'] = "Administratoren";
$locale['202'] = "Artikel Kategorien";
$locale['203'] = "Artikel";
$locale['204'] = "Blacklist";
$locale['205'] = "Kommentare";
$locale['206'] = "Eigene Seiten";
$locale['207'] = "Datenbank Backup";
$locale['208'] = "Download Kategorien";
$locale['209'] = "Downloads";
$locale['210'] = "FAQs";
$locale['211'] = "Foren";
$locale['212'] = "Bilder";
$locale['213'] = "Infusionen";
$locale['214'] = "Infusionen";
$locale['215'] = "Mitglieder";
$locale['216'] = "News";
$locale['217'] = "Panels";
$locale['218'] = "Fotoalben";
$locale['219'] = "PHP Info";
$locale['220'] = "Umfragen";
$locale['221'] = "";
$locale['222'] = "Seitenlinks";
$locale['223'] = "Einsendungen";
$locale['224'] = "Update";
$locale['225'] = "Benutzergruppen";
$locale['226'] = "Weblink Kategorien";
$locale['227'] = "Weblinks";
$locale['228'] = "Haupteinstellungen";
$locale['229'] = "Zeit- und Datumseinstellungen";
$locale['230'] = "Foren Einstellungen";
$locale['231'] = "Registrationseinstellungen";
$locale['232'] = "Fotogalerie Einstellungen";
$locale['233'] = "Sonstige Einstellungen";
$locale['234'] = "Private Nachrichten Einstellungen";
$locale['235'] = "News Kategorien";
$locale['236'] = "BB-Codes";
$locale['237'] = "Smileys";
$locale['238'] = "Benutzerfelder";
$locale['239'] = "Forum R&auml;nge";
$locale['240'] = "Benutzerfelder Kategorien";
$locale['241'] = "News";
$locale['242'] = "Benutzer Verwaltung";
$locale['243'] = "Downloads";
$locale['244'] = "St&uuml;ck pro Seite";
$locale['245'] = "Banner";
$locale['246'] = "Sicherheit";
$locale['247'] = "Benutzer Verwaltung";
$locale['248'] = "Admin Passwort zur&uuml;cksetzen";
$locale['249'] = "Fehlerlog";

// Seiteninformationen
$locale['250'] = "Informationen";
$locale['251'] = "Registrierte Mitglieder:";
$locale['252'] = "Unaktivierte Mitglieder:";
$locale['253'] = "Gesperrte Mitglieder (Sicherheitssperre):";
$locale['254'] = "Eingesendete News:";
$locale['255'] = "Eingesendete Artikel:";
$locale['256'] = "Eingesendete Weblinks:";
$locale['257'] = "Kommentare:";
$locale['258'] = "";
$locale['259'] = "Forum Beitr&auml;ge:";
$locale['260'] = "Eingesendete Fotos:";
$locale['261'] = "Fotos gesamt:";
$locale['262'] = "Aktive Mitglieder:";
$locale['263'] = "Suspendierte Mitglieder:";
$locale['264'] = "Inaktive Mitglieder:";
$locale['265'] = "Eingesendete Downloads:";

?>